### ISSUE TITLE
Readme ist not up to date

### ISSUE THREAD

**Issue by jbchr** [keen/keen-botkit#2]
Hey guys,

just wanted to let you know, that your Readme is not up to date. The code

`
var receiveMiddleware = KeenBotKitIntegration.botKitReceiveMiddleware(client);
var sendMiddleware = KeenBotKitIntegration.botKitSendMiddleware(client);
`

fails because the *payloadMiddleware* expects the options object to be defined. You should either update the Readme or check for that case in the payloadMiddleware.

Bests.

**Comment by nemo** [comment]
Thanks @jbchr. Just fixed this one :)
